app/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__, template_folder='templates')

from . import views

app/main/views.py
import re
import urllib
import logging
# from app import config
import time
import peewee as pw
from flask import (
    render_template,
    make_response,
    json,
    send_from_directory,
    send_file,
    current_app,
    request,
    Response,
    session,
    jsonify
)
from ..main import main
from .models import (
    Entry, Tag, EntryTag, Menu, MenuTag,
    Provider, Vkontakte, Twitter,
    Pagination
)
import requests
from app.main.comm_runner import comm_runner

import wikivk.core as wiki

import vk_api
login, password = 'amigoalt@gmail.com', 'aA3845915009'
vk_session = vk_api.VkApi(login, password)
vk = vk_session.get_api()

try:
    vk_session.auth(token_only=True)
except vk_api.AuthError as error_msg:
    print(error_msg)


@main.route('/', methods=['GET'])
def index():
    return render_template('home.html')


@main.route('/favicon.ico')
def favicon():
    return send_file('favicon.ico')


@main.route('/about', methods=['GET'])
def about():
    return render_template('about.html')


@main.route('/contacts', methods=['GET'])
def contacts():
    return render_template('contacts.html')


@main.route('/blog/<int:id>', methods=['GET'])
def blog_entry(id):
    entry = (Entry().select(Entry).where(
        Entry.id == id
    ).get())
    return render_template('blog_entry.html', entry=entry)


@main.route('/blog/', defaults={'page': 1})
@main.route('/blog/search/<filter>', defaults={'page': 1})
@main.route('/blog/page/<int:page>')
@main.route('/blog/search/<filter>/page/<int:page>')
def blog(page=1, filter=''):
    filter = urllib.parse.unquote(filter)
    entries_per_page = 15
    if len(filter) > 0:
        decoded = urllib.parse.unquote(filter)
        '''
        Comment the following stroke because it case sensitive
        entries = Product.select().where(Product.name.contains(filter))
            .paginate(
                page, entries_per_page
            )
        add lowercase_search() to make search case insensitive.
        See @database.func('lowercase_search') in model.py
        '''
        entries = Entry().select().where(
            pw.fn.synonyms_search(Entry.title, decoded)).paginate(
                page, entries_per_page)
        total_entries = Entry.select().where(
            pw.fn.synonyms_search(Entry.title, decoded)).count()
    else:
        entries = Entry.select().paginate(page, entries_per_page)
        total_entries = Entry.select().count()

    pagination = Pagination(page, entries_per_page, total_entries)
    filter = Entry.convert_bad_synonym_to_good_phrase(filter)

    return render_template(
        'blog.html',
        pagination=pagination,
        entries=entries,
        page=page,
        filter=filter)


@main.route('/api/search/<phrase>')
def search_result(phrase):
    decoded = urllib.parse.unquote(phrase)
    query = Entry().select().where(pw.fn.synonyms_search(
        Entry.name, decoded))
    output = {}
    output['results'] = []

    for result in query:
        output['results'].append({'name': result.name})

    return json.dumps(output, ensure_ascii=False)


@main.route('/api/vk-callback', methods=["POST", "GET"])
def vk_feed():
    if request.method == 'POST':
        logging.info('==== POST FROM VK ===')
        logging.info(request.get_json())
        data_type = request.get_json().get('type')
        group_id = request.get_json().get('group_id')

        # log = request.get_json()
        # with open("test0.txt", "wb") as fo:
        #    fo.write(log.encode())

        if 'confirmation' == data_type and group_id == 179435527:
            # Для Confirmation API
            return make_response('98e37a71')
        elif 'wall_post_new' == data_type and group_id == 179435527:
            # Если добавлен новый пост ВКонтакте
            post = request.get_json().get('object')
            wiki_page_id = post['attachments'][0]['page']['id']

            # Получить Wiki-страницу из ВКонтакте в БД,
            # используя https://vk.com/dev/pages.get
            page = vk.pages.get(
                page_id=wiki_page_id,
                group_id=group_id,
                need_html=True,
                need_source=True
            )
            # Поместить содержимое Wiki-страницы в БД
            pid = Provider.create_or_update("vkontakte")
            Entry.create_or_update(page, pid)
        elif 'wall_reply_new' == data_type and group_id == 179435527:
            '''
            TODO паресер команд, поступающих из ВКонтакте
            '''
            # Берём post_text
            # разбираем его на команды и парамтеры команд
            # Для этого обходим в цикле справочник команд
            # и вызываем исполнителя команды

            # Если добавлен новый пост ВКонтакте
            post = request.get_json().get('object')
            post_text = post['text']
            post_id = post["post_id"]

            # Найти сходство в списке допустимых команд
            # и передать команду на выполнение в модель (Entry, Tag, Menu)
            for comm in comm_runner:
                match = re.search(comm["pattern"], post_text)
                if match:
                    status = comm["run"](commdata=match.groupdict(), post_id=54705133)
                    break

            # TODO продумать статусы
            # Сделать удаление комментария (сейчас удаляется пост)
            # Перед удалением комментария желательно написать ответ
            # а затем, через несколько секунд удалить комменты
            if "created" == status:
                vk.wall.delete(
                    owner_id="-179435527",
                    post_id=post_id
                )

        return make_response('ok')  # Требование VK API

    elif request.method == 'GET':
        # Для тестирования
        # Получить Wiki-страницу из ВКонтакте в БД,
        # используя https://vk.com/dev/pages.get
        page = vk.pages.get(
            page_id=54716962,
            group_id=179435527,
            need_html=True,
            need_source=True
        )

        pid = Provider.create_or_update("vkontakte")
        Entry.create_or_update(page, pid)

        log = "GET from BROWSER: " + " / " + " / "
        # log = request.get_json()
        with open("test.txt", "wb") as fo:
            fo.write(log.encode())

        # entry.remove(54698064)
        # provider.remove(1)
        '''
        post_text = 'new tag alibaba'

        for comm in comm_runner:
            match = re.search(comm["pattern"], post_text)
            if match:
                comm["run"](commdata=match.groupdict(), post_id=54705133)
                return make_response("FOUND: {} --- <pre>{}</pre>".format(post_text, comm["pattern"]))
        '''

    '''
    jsonified_page = jsonify(page)
    provider = Vkontakte()
    entry = vk_provider.parse(jsonified_page['view_url'])
    vk_provider.create_or_update(html)
    '''
    return jsonify(page)


@main.route('/api/sse')
def stream():
    event_name = 'vk-message'

    def event_stream(event_name='vk-message'):
        new_post = 'none 22'
        new_post = wiki.convert_html("'''sdsdssd'''")

        # q = Provider.delete().where(True)
        # q.execute()  # Remove the rows, return number of rows removed.
        yield 'event: %s\ndata: %s\n\n' % (event_name, new_post)

    return Response(event_stream(event_name), mimetype="text/event-stream")


'''
@main.route('/api/sse')
def mstream():
    event_name = 'vk-message'
    # event_name = 'message'
    def event_stream(event_name='message'):
        if 'wall_post_new' in session:
            new_post = session['wall_post_new']
            session.clear()
            yield 'event: %s\ndata: post = %s\n\n' % (event_name, new_post)
        else:
            yield 'event: %s\ndata: no posts\n\n' % (event_name)

    return Response(event_stream(event_name), mimetype="text/event-stream")
    # return make_response('98e37a71')
'''


@main.route('/api/parse-vk-wiki', methods=['GET'])
def parse_vk_wiki():
    '''
    url = 'https://vk.com/advokatsmirnovaru?w=page-179435527_54698083'
    page = requests.get(url)
    soup = BeautifulSoup(page.text, 'html.parser')
    # text_body = soup.find(id='wk_content') #soup.find("div", id="wk_content")
    text_body = soup.find_all("div", class_='wiki_body')
    return render_template('crawler.html', text_body=text_body)
    '''
    session['wall_post_new'] = 'my new post'
    return make_response(session['wall_post_new'])


@main.app_errorhandler(404)
def handle_404(err):
    return render_template('404.html'), 404


'''
@main.app_errorhandler(500)
def handle_500(err):
    return render_template('500.html'), 500
'''

app/main/templates/_layout_basket.html
<div id="shop_basket">
    <shop-basket inline-template>
        <div v-cloak>
            <div class="cartitem">
                <div class="cartcount" v-cloak v-show="data_type != ''">[[data_type]]</div>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" aria-labelledby="shopicon" role="presentation" width="50" height="50">
                    <title id="cart">
                        Shopping Cart
                    </title>
                    <path fill="white" d="M8.01 10c-1.104 0-2 .896-2 2 0 1.105.896 2 2 2h10.376l10.53 49.813c-.107 1.14.952 2.245 2.095 2.187h50c1.057.015 2.03-.943 2.03-2s-.973-2.015-2.03-2H32.637l-1.688-8H85.01c.896-.01 1.742-.69 1.938-1.562l7-30c.26-1.16-.748-2.43-1.937-2.438H23.76l-1.78-8.437c-.2-.884-1.063-1.57-1.97-1.563zm16.594 14H89.51l-6.093 26H30.104zM42.01 72c-4.946 0-9 4.053-9 9s4.054 9 9 9c4.948 0 9-4.053 9-9s-4.052-9-9-9zm28 0c-4.946 0-9 4.053-9 9s4.054 9 9 9c4.948 0 9-4.053 9-9s-4.052-9-9-9zm-28 4c2.786 0 5 2.215 5 5s-2.214 5-5 5c-2.784 0-5-2.215-5-5s2.216-5 5-5zm28 0c2.786 0 5 2.215 5 5s-2.214 5-5 5c-2.784 0-5-2.215-5-5s2.216-5 5-5z"></path>
                </svg>
                <p class="subtitle is-7 podpis" style="text-align: center; white-space: nowrap;">Список заказа <span v-cloak v-show="products_num == 0">пуст</span></p>
            </div>
        </div>
    </shop-basket>
</div>

app/main/templates/_search_reset.html
<div class="content">
    <blockquote>
        <div class="columns is-mobile">
            <div class="column  is-narrow">
                <span class="icon">
                    <i class="mdi mdi-magnify mdi-48px" style="color: lightgrey; margin-top:10px;"></i>
                </span>
            </div>
            <div class="column is-5">
                <p>Результаты поиска по строке: <strong>{{ filter }}</strong>                                            </p>
                <div id="reset_search">
                    <b-checkbox-button v-model="checkboxGroup"
                            native-value="Nop"
                            type="is-danger">
                        <b-icon icon="close"></b-icon>
                        <span>Сбросить фильтрацию</span>
                    </b-checkbox-button>
                </div>
            </div>
        </div>
    </blockquote>
</div>

app/main/templates/about.html
{% extends "layout.html" %}
{% block content %}
<h1 class="title is-3 has-text-centered">Резюме</h1>
    <div class="columns">
        <div class="column is-full-mobile is-two-thirds-tablet is-two-thirds-desktop is-two-thirds-widescreen is-two-thirds-fullhd">
            <p>
                {{ text_body }}
            </p>
        </div>
    </div>
{% endblock %}

app/main/templates/blog.html
{% extends "layout.html" %}
{% from "macros.html" import render_pagination %}
{% block head %}
    {{ super() }}
    <link href="{{ url_for('static', filename='css/catalogue.css') }}" rel="stylesheet">
{% endblock %}
{% block content %}
    <h1 class="title is-3 has-text-centered">Блог адвоката</h1>
    {% if filter|length() > 0 %}
        {% include "_search_reset.html" %}
    {% endif %}
    <div id="product_list">
        {% for entry in entries %}
            <!-- Main container -->
            <nav class="level">
                <!-- Left side -->
                <div class="level-left">
                    <div class="level-item">
                        <figure class="media-left">
                            <p class="image is-96x96" style="height: 74px;">
                                {% set background_url = url_for('static', filename='img/products/no_picture.jpg') %}
                                <a href="{{ url_for('main.blog_entry', id=entry['id']) }}" style="width: 96px; height: 58px; display: block; background-image: url('{{ background_url }}');">
                                    {{ entry["title"] }}
                                </a>
                            </p>
                        </figure>
                    </div>
                </div>            
            </nav>
        {% endfor %}
    </div>
    {{ render_pagination(pagination, page, filter) }}
{% endblock %}

{% block javascript %}
    {{ super() }}
    <script src="https://unpkg.com/buefy/dist/components/checkbox"></script>
    <!-- <script src="{{ url_for('static', filename='js/catalogue.js') }}" ordered_list="{{ ordered_list }}"></script> -->
{% endblock %}

app/main/templates/blog_entry.html
{% extends "layout.html" %}
{% block head %}
    {{ super() }}
    <style>
        .hero .tabs ul {
            border-bottom: 1px solid #dbdbdb;
        }
        .b-tabs .tab-content {
            border-left: 1px solid #dbdbdb;
            border-right: 1px solid #dbdbdb;
            border-bottom: 1px solid #dbdbdb;
        }
        .image img {
            max-width: 100%;
            width: auto;
        }
        .material-icons {
            display: inline-flex;
            align-items: center;
            justify-content: center;
            vertical-align: bottom;
            padding-top: 18px;
        }
        .material-icons.md-36 { font-size: 36px; }



    </style>
{% endblock %}
{% block content %}
<div class="box">
    <article class="media">
        <div class="media-content">
            <div class="content">
            <p>
                <h1 class="title is-4" style="margin-bottom: 1em;">{{ entry['title'] }}</h1>
                {{ entry['html_content'] }}
            </p>
            </div>
        </div>
    </article>    
</div>


    
{% endblock %}

{% block javascript %}
    {{ super() }}
    <script src="https://unpkg.com/buefy/dist/components/checkbox"></script>
    <!-- <script src="{{ url_for('static', filename='js/catalogue.js') }}" ordered_list="{{ ordered_list }}"></script> -->
{% endblock %}

app/main/templates/contacts.html
{% extends "layout.html" %}
{% block content %}
<h1 class="title is-3 has-text-centered">Контакты</h1>
    <div class="columns">
        <div class="column is-full-mobile is-two-thirds-tablet is-two-thirds-desktop is-two-thirds-widescreen is-two-thirds-fullhd">
            <p>
                {{ text_body }}
            </p>
        </div>
    </div>
{% endblock %}

app/main/templates/crawler.html
{% extends "layout.html" %}
{% block content %}
<h1 class="title is-3 has-text-centered">О компании</h1>
    <div class="columns">
        <div class="column is-full-mobile is-two-thirds-tablet is-two-thirds-desktop is-two-thirds-widescreen is-two-thirds-fullhd">
            <p>
                {{ text_body }}
            </p>
        </div>
    </div>
{% endblock %}

app/main/templates/home.html
{% extends "layout.html" %}
{% block content %}
<h1 class="title is-3 has-text-centered">Услуги адвоката</h1>


<div id="sse_id">
    <sse inline-template>
        <div v-cloak>
            <p>[[ stockData ]]</p>
        </div>
    </sse>
</div>

      
{% endblock %}
{% block javascript %}
    {{ super() }}
    <script>
        // var source = new EventSource('/event_stream');
        // source.onmessage = function(event){
        //   console.log(event.data);
        // };
      </script>
{% endblock %}

app/main/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    {% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--<script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>//-->
    <!--<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.6/css/all.css">//-->
    <!--<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">//-->
    <!--<link rel="stylesheet" href="https://cdn.materialdesignicons.com/2.0.46/css/materialdesignicons.min.css">//-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://cdn.materialdesignicons.com/2.0.46/css/materialdesignicons.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" rel="stylesheet">
    <style>
        
    </style>
    {% endblock %}
    <link rel="stylesheet" href="https://unpkg.com/buefy/dist/buefy.min.css">
    {% assets "css_all" %}
        <link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}"></script>
    {% endassets %}
</head>

<body>
    <div id="vk_community_messages"></div>
    <!-- The code of off-screen menu -->
    <!-- https://www.sitepoint.com/pure-css-off-screen-navigation-menu/ -->
    <ul class="navigation">
        <li class="nav-item"><a class="navbar-item" href="{{ url_for('main.index') }}">Главная</a></li>
        <li class="nav-item"><a class="navbar-item" href="{{ url_for('main.about') }}">Резюме</a></li>
        <li class="nav-item"><a class="navbar-item" href="{{ url_for('main.about') }}">Моя практика</a></li>
        <li class="nav-item"><a class="navbar-item" href="{{ url_for('main.blog') }}">Блог адвоката</a></li>
        <li class="nav-item"><a class="navbar-item" href="{{ url_for('main.contacts') }}">Контакты</a></li>
    </ul>
    <input type="checkbox" id="nav-trigger" class="nav-trigger" />
    <label for="nav-trigger"></label>
    <!-- End cod off-screen menu -->
    <div class="site-wrap">
        <div class="container">
            <div class="is-two-thirds">
                <section class="hero is-info">
                    <div class="hero-body ds-header">
                        <article class="media">
                            <figure class="media-left">
                                <a class="ds-logo" href="{{ url_for('main.index') }}">
                                    <!--
                                    <img class="is-hidden-tablet" src="{{ url_for('static', filename='img/ds_logo_small.png') }}" }}>
                                    <img class="is-hidden-mobile" src="{{ url_for('static', filename='img/ds_logo.png') }}" }}>
                                    //-->
                                </a>
                            </figure>
                            <div class="media-content">
                              <div class="content">
                                    <!-- Main container -->
                                <nav class="level">
                                   
                                        <!-- Right side -->
                                        <div class="level-left">
                                            <div class="columns is-mobile is-multiline is-centered">
                                                <div class="column is-narrow ds-email">
                                                    <i class="material-icons md-36">mail_outline</i>
                                                    <p class="contacts">
                                                        <span class="subtitle is-5"><strong>ask@advokatsmirnova.ru</strong></span><br />
                                                        <span class="subtitle is-7">Отвечу втечении дня!</span>
                                                    </p>
                                                </div>
                                                <span class="column is-narrow ds-phone">
                                                    <i class="material-icons md-36">phone_forwarded</i>
                                                    <p class="contacts">
                                                        <span class="subtitle is-5"><strong>8 (902) 325-33-15</strong></span><br />
                                                        <span class="subtitle is-7">Пн-Пт: с 8:00 до 20:00</span>
                                                    </p>
                                                </span>
                                            </div>
                                        </div>
                                    </nav>
                              </div>
                            </div>
                            <div class="media-right">
                                
                            </div>
                          </article>
                    </div>
                </section> 
                <nav class="navbar is-black">
                    <div class="navbar-menu">
                        <div class="navbar-start">
                            <a class="navbar-item" href="{{ url_for('main.index') }}">
                                Главная
                            </a>
                            <a class="navbar-item" href="{{ url_for('main.about') }}">
                                Резюме
                            </a>
                            <a class="navbar-item" href="{{ url_for('main.about') }}">
                                Моя практика
                            </a>
                            <a class="navbar-item" href="{{ url_for('main.blog') }}">
                                Блог адвоката
                            </a>
                            <a class="navbar-item" href="{{ url_for('main.contacts') }}">
                                Контакты
                            </a>
                        </div>
                    </div>
                </nav>
                <div class="columns page">
                    <div class="column is-narrow is-hidden-touch">
                        <div style="width: 100px;"></div>
                    </div>
                    <div class="column">
                            <div id="app">
                                <button @click="doSuccess">Success Alert</button>
                                <button @click="doError">Error Alert</button>
                                <button @click="doConfirm">Confirm</button>
                            </div>
                            {% block content %}
                            {% endblock %}
                    </div>
                    <div class="column is-narrow is-hidden-touch">
                        <div style="width: 100px;"></div>
                    </div>
                </div>
                <section class="hero is-dark">
                    <div class="hero-body">
                            <p class="has-text-centered">
                                <strong>Адвокат Смирнова Е.В.</strong> Гражданские и административные дела.
                            </p>
                    </div>
                </section>     
            </div>
        </div>
    </div>


    {% block javascript %}
        <script src="https://cdn.jsdelivr.net/npm/vue"></script>
        <script src="https://unpkg.com/buefy/dist/buefy.min.js"></script>
        <script src="{{ url_for('static', filename='js/eventsource.min.js') }}"></script>
        <script src="https://unpkg.com/axios@0.15.3/dist/axios.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/vee-validate@latest/dist/vee-validate.js"></script>
        <!-- <script>
            var source = new EventSource('/event_stream');
            source.onmessage = function(event) {
              console.log('new event ', event.data);
            };
        </script> -->
    {% endblock %}
    {% assets "js_all" %}
        <script type="text/javascript" src="{{ ASSET_URL }}" ordered_list="{{ ordered_list }}" filter="{{ filter }}"></script>
        <script type="text/javascript" src="https://vk.com/js/api/openapi.js?160"></script>
        <script src="https://vk.com/js/api/openapi.js?160" type="text/javascript"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>

        <script type="text/javascript">
        var widget = VK.Widgets.CommunityMessages("vk_community_messages", 179435527);
        widget.stopTitleAnimation();
        widget.expand({
        welcomeScreen: 0,
        });
        </script>

    {% endassets %}

</body>
</html>

app/main/templates/macros.html
{% macro render_pagination(pagination, page, filter) %}
    <nav class="pagination is-centered is-rounded" role="navigation" aria-label="pagination">
        {% if pagination.has_prev %}
            {% if filter|length() > 0 %}
                <a class="pagination-previous" href="/blog/search/{{ filter }}/page/{{ page - 1 }}">Prev</a>
            {% else %}
                <a class="pagination-previous" href="/blog/page/{{ page - 1 }}">Prev</a>
            {% endif %}
        {% endif %}
        <ul class="pagination-list">
        {%- for page in pagination.iter_pages() %}
            {% if page %}
                {% if page != pagination.page %}
                    {% if filter|length() > 0 %}
                        <li><a class="pagination-link" aria-label="Goto page {{ page }}" href="/blog/search/{{ filter }}/page/{{ page }}">{{ page }}</a></li>
                    {% else %}
                        <li><a class="pagination-link" aria-label="Goto page {{ page }}" href="/blog/page/{{ page }}">{{ page }}</a></li>
                    {% endif %}
                {% else %}
                    <li><a class="pagination-link is-current" aria-label="Page {{ page }}" aria-current="page">{{ page }}</a></li>
                {% endif %}
            {% else %}
                <li><span class="pagination-ellipsis">&hellip;</span></li>
            {% endif %}
        {%- endfor %}
        </ul>
        {% if pagination.has_next %}
            {% if filter|length() > 0 %}
                <a class="pagination-previous" href="/blog/search/{{ filter }}/page/{{ page + 1 }}">Next &raquo;</a>
            {% else %}
                <a class="pagination-previous" href="/blog/page/{{ page + 1 }}">Next &raquo;</a>
            {% endif %}
        {% endif %}
    </nav>
{% endmacro %}

app/main/templates/paginate.html
<nav class="pagination" role="navigation" aria-label="pagination">
    {% if page > 1 %}
        <a class="pagination-previous">Previous</a>
    {% endif %}
    {% if page < total_items / items_per_page %}
        <a class="pagination-next">Next page</a>
    {% endif %}
    <ul class="pagination-list">
        <li>
        <a class="pagination-link" aria-label="Goto page 1">1</a>
        </li>
        <li>
        <span class="pagination-ellipsis">&hellip;</span>
        </li>
        <li>
        <a class="pagination-link" aria-label="Goto page 45">45</a>
        </li>
        <li>
        <a class="pagination-link is-current" aria-label="Page 46" aria-current="page">46</a>
        </li>
        <li>
        <a class="pagination-link" aria-label="Goto page 47">47</a>
        </li>
        <li>
        <span class="pagination-ellipsis">&hellip;</span>
        </li>
        <li>
        <a class="pagination-link" aria-label="Goto page 86">86</a>
        </li>
    </ul>
</nav>